INSERT INTO csc667.wordlist(word, category) VALUES ('cat', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('sun', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('cup', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('ghost', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('flower', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('pie', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('cow', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('banana', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('snowflake', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bug', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('book', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('jar', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('snake', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('light', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('tree', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('lips', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('apple', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('slide', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('socks', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('smile', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('swing', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('coat', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('shoe', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('water', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('heart', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('hat', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('ocean', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('kite', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('dog', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('mouth', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('milk', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('duck', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('eyes', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('skateboard', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bird', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('boy', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('apple', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('person', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('girl', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('mouse', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('ball', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('house', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('star', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('nose', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bed', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('whale', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('jacket', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('shirt', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('hippo', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('beach', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('egg', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('face', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('cookie', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('cheese', 'easy');
--INSERT INTO csc667.wordlist(word, category) VALUES ('ice cream cone', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('drum', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('circle', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('spoon', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('worm', 'easy');
--INSERT INTO csc667.wordlist(word, category) VALUES ('spider web', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bridge', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bone', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('grapes', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bell', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('jellyfish', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bunny', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('truck', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('grass', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('door', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('monkey', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('spider', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bread', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('ears', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bowl', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bracelet', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('alligator', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bat', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('clock', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('lollipop', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('moon', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('doll', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('orange', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('ear', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('basketball', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bike', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('airplane', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('pen', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('inchworm', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('seashell', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('rocket', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('cloud', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bear', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('corn', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('chicken', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('purse', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('glasses', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('blocks', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('carrot', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('turtle', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('pencil', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('horse', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('dinosaur', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('head', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('lamp', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('snowman', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('ant', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('giraffe', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('cupcake', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('chair', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('leaf', 'easy');
--INSERT INTO csc667.wordlist(word, category) VALUES ('bunk bed', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('snail', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('baby', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('balloon', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('bus', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('cherry', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('crab', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('football', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('branch', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('robot', 'easy');
INSERT INTO csc667.wordlist(word, category) VALUES ('horse', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('door', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('song', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('trip', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('backbone', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('bomb', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('round', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('treasure', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('garbage', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('park', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('pirate', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('ski', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('state', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('whistle', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('palace', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('baseball', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('coal', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('queen', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('dominoes', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('photograph', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('computer', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('hockey', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('aircraft', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('hotdog', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('salt and pepper', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('key', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('ipad', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('whisk', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('frog', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('lawnmower', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('mattress', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('pinwheel', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('cake', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('circus', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('battery', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('mailman', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('cowboy', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('password', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('bicycle', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('skate', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('electricity', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('lightsaber', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('thief', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('teapot', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('deep', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('spring', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('nature', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('shallow', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('toast', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('outside', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('America', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('roller blading', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('gingerbread man', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('bowtie', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('half', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('spare', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('wax', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('light bulb', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('platypus', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('music', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('sailboat', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('popsicle', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('brain', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('birthday cake', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('skirt', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('knee', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('pineapple', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('tusk', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('sprinkler', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('money', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('spool', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('lighthouse', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('doormat', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('face', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('flute', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('rug', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('snowball', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('purse', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('owl', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('gate', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('suitcase', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('stomach', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('doghouse', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('pajamas', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('bathroom scale', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('peach', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('newspaper', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('watering can', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('hook', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('school', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('beaver', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('french fries', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('beehive', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('beach', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('artist', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('flagpole', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('camera', 'medium');
--INSERT INTO csc667.wordlist(word, category) VALUES ('hair dryer', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('mushroom', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('toe', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('pretzel', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('tv', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('quilt', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('chalk', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('dollar', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('soda', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('chin', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('swing', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('garden', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('ticket', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('boot', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('cello', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('rain', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('clam', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('pelican', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('stingray', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('fur', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('blowfish', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('rainbow', 'medium');
INSERT INTO csc667.wordlist(word, category) VALUES ('happy', 'medium');
/*INSERT INTO csc667.wordlist(word, category) VALUES ('snag', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('mime', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('hail', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('jungle', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('important', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('peasant', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('baggage', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('clog', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pizza sauce', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('password', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('heinz 57', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('scream', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('newsletter', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bookend', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pro', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dripping', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pharmacist', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('lie', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('catalog', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ringleader', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('husband', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('laser', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('diagonal', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('comfy', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('myth', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dorsal', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('biscuit', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('hydrogen', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('macaroni', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('rubber', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('darkness', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('yolk', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('exercise', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('vegetarian', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('shrew', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('chestnut', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ditch', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('wobble', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('glitter', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('neighborhood', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dizzy', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('fireside', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('retail', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('drawback', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('logo', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('fabric', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('mirror', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('barber', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('jazz', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('migrate', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('drought', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('commercial', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dashboard', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bargain', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('double', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('download', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('professor', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('landscape', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ski goggles', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('vitamin', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('quarter', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cardboard', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('oar', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('babysitter', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('drip', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('shampoo', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('point', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('time machine', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('yardstick', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('think', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('lace', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('darts', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('world', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('avocado', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bleach', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('shower curtain', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('extension cord', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dent', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('birthday', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('lap', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('sandbox', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bruise', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('quicksand', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('fog', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('gasoline', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pocket', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('honk', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('sponge', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('rim', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bride', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('wig', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('zipper', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('wag', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('letter opener', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('fiddle', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('water buffalo', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pilot', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('brand', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pail', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('baguette', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('rib', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('mascot', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('fireman pole', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('zoo', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('sushi', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('fizz', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ceiling fan', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bald', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('banister', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('punk', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('post office', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('season', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('internet', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('chess', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('puppet', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('chime', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ivy', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('full', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('koala', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dentist', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('baseboards', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ping pong', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bonnet', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('mast', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('hut', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('welder', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dryer sheets', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('sunburn', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('houseboat', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('sleep', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('kneel', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('crust', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('grandpa', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('speakers', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cheerleader', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dust bunny', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('salmon', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cabin', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('handle', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('swamp', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cruise', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('wedding cake', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('crow\'s nest', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('macho', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('drain', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('foil', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('orbit', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('dream', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('recycle', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('raft', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('gold', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('plank', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cliff', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('sweater vest', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cape', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('safe', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('picnic', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('shrink ray', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('leak', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('boa constrictor', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('deep', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('mold', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cd', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('tiptoe', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('hurdle', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('knight', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('loveseat', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cloak', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bedbug', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('bobsled', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('hot tub', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('firefighter', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cell phone charger', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('beanstalk', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('nightmare', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('coach', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('moth', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('sneeze', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('wooly mammoth', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pigpen', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('swarm', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('goblin', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('chef', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('applause', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('wax', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('sheep dog', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('s\'mores', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('plow', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('runt', 'hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('vision', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('loiterer', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('observatory', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('century', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('atlantis', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('kilorgram', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('neutron', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('stowaway', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('psychologist', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('exponential', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('aristocrat', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('eureka', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('parody', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('cartography', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('figment', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('philosopher', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('tinting', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('overture', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('opaque', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('everglades', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ironic', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('zero', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('landfill', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('implode', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('czar', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('armada', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('crisp', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('stockholder', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('inquisition', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('mooch', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('gallop', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('archaeologist', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('blacksmith', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('addendum', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('upgrade', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('hang ten', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('acre', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('twang', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('mine car', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('protestant', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('brunette', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('stout', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('quarantine', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('tutor', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('positive', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('champion', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pastry', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('tournament', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('chick-fil-a', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('rainwater', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('random', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('lyrics', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ice fishing', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('clue', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('flutter', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('slump', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('ligament', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('flotsam', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('siesta', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('pomp', 'really hard');
INSERT INTO csc667.wordlist(word, category) VALUES ('', 'really hard');
*/